## 2. np.zeros()
Return a new array of given shape and type, filled with zeros.

### Syntax:
```python
np.zeros(shape, dtype=float, order='C', *, like=None)
```

In [1]:
# importing numpy
import numpy as np

### 1-D array

In [3]:
# creating a 1-D array filled with zeros

array = np.zeros((5))
array

array([0., 0., 0., 0., 0.])

In [4]:
# printing datatype of array
array.dtype

dtype('float64')

### 2-D Array

In [5]:
# creating 2-D Array
array2 = np.zeros((2,5),dtype=np.int8)
array2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### n-D Array

In [6]:
# creating 4-D array
array3 = np.zeros((2,2,2,2))
array3

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])