## 4. np.arange()
Return evenly spaced values within a given interval.

### Syntax:
```python
np.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)
```

In [2]:
import numpy as np

### np.arange(stop)
Values are generated within the half-open interval `[0, stop)` (in other words, the interval including start but excluding stop).

In [3]:
# get evenly space values upto 20
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### np.arange(start, stop)
Values are generated within the half-open interval `[start, stop)` 

In [4]:
array2 = np.arange(5,25)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

### np.arange(start, stop, step)
Values are generated within the half-open interval `[start, stop)`, with spacing between values given by `step`.

In [5]:
array3 = np.arange(10,25, 2)

# printing array3 with values spaced with 2
print(array3)

# reshaping the array into 2d array
array3.reshape((2,4))

[10 12 14 16 18 20 22 24]


array([[10, 12, 14, 16],
       [18, 20, 22, 24]])