## 6. np.empty()

Return a new array of given shape and type, without initializing entries.

### Syntax:
```python
np.empty(shape, dtype=float, order='C', *, device=None, like=None)
```

In [2]:
# import numpy
import numpy as np

### Create an Empty Array

In [3]:
# create an empty array
array = np.empty((2,5))

# print the array
array


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.33772113e-307, 2.67018641e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.42419530e-306]])

### Intialize the array

In [10]:
# assign the value to specific index
array[0, 1] = 3

array

array([[0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# assign the value to entire row
array[0] = 5

array

array([[5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0.]])

In [12]:
# assign the same value to entire array
array[:] = 12

array

array([[12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.]])

In [14]:
# assign list of values

array[1] = [1,2,3,4,5]

array

array([[12., 12., 12., 12., 12.],
       [ 1.,  2.,  3.,  4.,  5.]])