## 2. Slicing

Slicing in python means taking elements from one given index to another given index.

### Syntax:

`array[start:stop]`

`array[start:stop:step]`

In [2]:
# import numpy
import numpy as np
from io import StringIO

In [3]:
text = """
        1 2 3 4 5
        6 7 8 9 10 
        11 12 13 14 15"""
        
array = np.genfromtxt(StringIO(text), dtype=np.int16, delimiter=" ")

array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int16)

In [4]:
# slicing elements in 1st row from 2nd to 4th elemement
print(array[0][1:5])

# slicing elements in 2nd row from 1st to 3rd element
print(array[1][:4])

[2 3 4 5]
[6 7 8 9]


In [5]:
# using step
print(array[::2])

array2 = np.array(['1', 2, 3, 4, 5])
array2

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


array(['1', '2', '3', '4', '5'], dtype='<U21')